[package]
name = "qc-alloc"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.172"
once_cell = "1.21.3"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
